In [23]:
from scipy import signal
import numpy as np

In [14]:
x = np.arange(9);

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
signal.welch(x, window='hamming')

C:\Users\zstechly\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\signal\spectral.py:1773: UserWarning: nperseg = 256 is greater than input length  = 9, using nperseg = 9
  .format(nperseg, input_length))


(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444]),
 array([ 1.19803724, 17.65433182,  0.23870809,  0.0725656 ,  0.0725717 ]))

In [1]:
test_array = range(10)

In [2]:
test_array

range(0, 10)

In [8]:
test_array = [1,2,3,4,5,6]

In [9]:
test_array

[1, 2, 3, 4, 5, 6]

In [10]:
current_index = 2

In [11]:
sum(test_array[current_index-2:current_index+3])

15

In [13]:
5+10

15

In [19]:
hex(int((50e6+200)/150e6*2**48))

'0x55556bb3f4d6'

In [20]:
0x55555673AA1B/2**48*150e6

50000009.99999958

In [21]:
1/200e6

5e-09

In [57]:
slot = np.arange(256)*64;
frm = np.arange(1024);
mod_ratio = np.arange(64);

In [58]:
slot

array([    0,    64,   128,   192,   256,   320,   384,   448,   512,
         576,   640,   704,   768,   832,   896,   960,  1024,  1088,
        1152,  1216,  1280,  1344,  1408,  1472,  1536,  1600,  1664,
        1728,  1792,  1856,  1920,  1984,  2048,  2112,  2176,  2240,
        2304,  2368,  2432,  2496,  2560,  2624,  2688,  2752,  2816,
        2880,  2944,  3008,  3072,  3136,  3200,  3264,  3328,  3392,
        3456,  3520,  3584,  3648,  3712,  3776,  3840,  3904,  3968,
        4032,  4096,  4160,  4224,  4288,  4352,  4416,  4480,  4544,
        4608,  4672,  4736,  4800,  4864,  4928,  4992,  5056,  5120,
        5184,  5248,  5312,  5376,  5440,  5504,  5568,  5632,  5696,
        5760,  5824,  5888,  5952,  6016,  6080,  6144,  6208,  6272,
        6336,  6400,  6464,  6528,  6592,  6656,  6720,  6784,  6848,
        6912,  6976,  7040,  7104,  7168,  7232,  7296,  7360,  7424,
        7488,  7552,  7616,  7680,  7744,  7808,  7872,  7936,  8000,
        8064,  8128,

In [59]:
frame_start_index = slot % 3
frame_start_index

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [64]:
frame_start_index[256]

IndexError: index 256 is out of bounds for axis 0 with size 256